blank_issues_enabled: false
contact_links:
  - name: RolfMoleman/Terraform-Latest Bug Reports and Feature Requests
    url: https://github.com/RolfMoleman/Terraform-Latest/issues/new/choose
    about: RolfMoleman/Terraform-Latest, has it's own issue log.

  - name: RolfMoleman/Terraform-Latest Roadmap
    url: https://github.com/RolfMoleman/Terraform-Latest/blob/main/README.md
    about: View the Roadmap for the upcoming work planned on the RolfMoleman/Terraform-Latest.
