name: Automatically update terraform-latest.nuspec
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
on:
  create:
  workflow_dispatch: {}
    

jobs:
  job1:
    name: "auto-update"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        skip: ['renovate']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.3

      - name: Install AU module
        shell: pwsh
        run: |
          Install-Module -Name AU -Force -Confirm:$false
          Import-Module -Name AU -Force

      - name: Check if nuspec file exists
        shell: pwsh
        run: |
          if (-not (Test-Path -Path ./packages/terraform-latest.nuspec)) {
            Write-Error "No nuspec file found in the package directory"
            exit 1
          }

      - name: Build Module
        shell: pwsh
        run: ./packages/update_nuspec.ps1

      - name: Configure git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes to terraform-latest.nuspec
        run: |
          git add terraform-latest.nuspec
          git commit -m "[${{ matrix.skip }} skip] Update terraform-latest.nuspec"
        if: ${{ startsWith(github.ref, 'refs/heads/renovate') }}