name: Automatically update terraform.nuspec
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
on: create

jobs:
  job1:
    name: "auto-update"
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/dependabot/') || startsWith(github.ref, 'refs/heads/renovate/') }}
    steps:
      - uses: actions/checkout@v4
      - name: Install AU module
        run: |
          Install-Module -Name AU -Force -Confirm:$false
      - name: Build Module
        shell: pwsh
        run: ./.scripts/update_nuspec.ps1

      - name: Configure git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes to terraform.nuspec
        if: ${{ startsWith(github.ref, 'refs/heads/dependabot/') }}
        run: |
          git add terraform.nuspec
          git commit -m "[dependabot skip] Update terraform-latest.nuspec"

      - name: Commit changes to terraform.nuspec
        if: ${{ startsWith(github.ref, 'refs/heads/renovate/') }}
        run: |
          git add terraform.nuspec
          git commit -m "[renovate skip] Update terraform-latest.nuspec"
