name: Build
permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main

  workflow_dispatch: {}

jobs:
  renovate-merge-bot:
    name: "auto merge renovate"
    runs-on: ubuntu-latest
    steps:
      - name: Merge Renovate PRs
        uses: int128/renovate-merge-bot@v1.41.0
        with:
          github-app-id: ${{ secrets.BOT_APP_ID }}
          github-app-private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

  auto-merge:
    name: "auto merge dependabot"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Merge Dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          github-token: "${{ secrets.PAT }}"
          config: .github/auto-merge.yml
          target: minor

  terraform:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: pack .\packages\terraform-latest.nuspec

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: install -source . -force terraform-latest

      - name: Terraform Version
        run: terraform -version