name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  workflow_dispatch: {}

jobs:
  build-terraform:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.3

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: pack .\packages\terraform-latest.nuspec

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: install -source . -force terraform-latest

      - name: Terraform Version
        run: terraform -version

      - name: Save Choco package
        uses: actions/upload-artifact@v4.3.2
        with:
          name: terraform-latest
          path: "${{ github.workspace }}/*.nupkg"

  publish-terraform:
    runs-on: windows-latest

    needs: build-terraform

    steps:
      - name: Restore Choco package
        uses: actions/download-artifact@v4.1.6
        with:
          name: terraform-latest
          path: ${{ github.workspace }}

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: install -source . -force terraform-latest

      - name: Terraform Version
        run: terraform -version

      - name: Add Choco API Key
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: apikey --key ${{secrets.CHOCO_API_KEY}} --source https://push.chocolatey.org/

      - name: Publish (noop)
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: push --source https://push.chocolatey.org/
